Issue #32: Napraviti metode za aktivaciju i suspendovanje naloga
Nemanja0/OSI_Grupa17 pull request #59
Opened 2023-01-13 00:25 UTC by lukavidic

- Realizovane metode zahtjevane u tasku (NAPOMENA: nije trazen razlog za ponovnu aktivaciju, smatram da je nepotreban i da je to greska u SRS-u)
- Napravljena izmjena u metodi za brisanje naloga, dodana provjera da li je nalog klijentski, ako jeste brisu se svi njegovi dogadjaji
- Izmjenjena funkcija u klasi Event koja brise sve ulaznice, ispravljen je propust da uklonjene ulaznice ostaju u korisnickim listama kupljenih ulaznica
- U Main klasi dodati potrebne varijable za rad sa suspenzijom i sve odgovarajuce provjere prilikom logina
- Sa ovim taskom gotov je i administratorski meni za upravljanje nalozima

2023-01-13 11:40 UTC, Nemanja0 requested changes

2023-01-13 11:40 UTC, Nemanja0 commented on Aplikacija/Softver_za_prodaju_ulaznica/src/users/Administrator.java
> +		while(true) {
Bilo bi dobro da se prije while petlje ispisu imena svih korisnika ciji je nalog aktiviran.

2023-01-13 11:41 UTC, Nemanja0 commented on Aplikacija/Softver_za_prodaju_ulaznica/src/users/Administrator.java
> +		while(true) {
Ostalo je u redu.

2023-01-13 11:47 UTC, Nemanja0 requested changes

2023-01-13 11:47 UTC, Nemanja0 commented on Aplikacija/Softver_za_prodaju_ulaznica/src/users/Administrator.java
> +					if(u.getUsername().equals(option)) {
Ovdje je potrebno provjeriti da li je nalog vec suspendovan, pa ispisati odgovarajucu poruku.

2023-01-13 11:47 UTC, Nemanja0 commented on Aplikacija/Softver_za_prodaju_ulaznica/src/users/Administrator.java
> +					if(u.getUsername().equals(option)) {
Ostalo mi djeluje uredno.

2023-01-13 15:49 UTC, Nemanja0 approved these changes
Sada sve djeluje uredno.

2023-01-14 17:07 UTC, radislavkosijer approved these changes
Sve je u redu nakon odradjenih izmjena.

2023-01-14 17:13 UTC, merged